### ISSUE TITLE
How to add ring-msg for my rslidar?

### ISSUE THREAD

**Issue by plumewind** [UMich-BipedLab/LiDARTag#1]
hello,

my rslidar is 32, but no ring. I want to add ring in the lidar_tag.cc:

lines496-500 in _getOrderBuff():
`pcl::PointCloud<PointXYZRI>::Ptr PclPointcloud(new pcl::PointCloud<PointXYZRI>);
   pcl::fromROSMsg(*msg, *PclPointcloud);
`

change to this:
`pcl::PointCloud<PointXYZRI>::Ptr PclPointcloud(new pcl::PointCloud<PointXYZRI>);
        pcl::PointCloud<pcl::PointXYZI>::Ptr PclPointcloud_raw(new pcl::PointCloud<pcl::PointXYZI>);
        pcl::fromROSMsg(*msg, *PclPointcloud_raw);
        _addRing(PclPointcloud_raw, PclPointcloud);`

but get error:
`[ INFO] [1586340483.356691067]: Start edge extraction on rslidar-32 

points size 53119 

test 1 in  _getOrderBuff()

test 1 in  _mainLoop()

[LiDARTag/lidar_tag-3] process has died [pid 24622, exit code -11, cmd /home/bran/catkin_tagcalib/devel/lib/lidar_tag/lidar_tag_main __name:=lidar_tag __log:=/home/bran/.ros/log/cfd224c6-7980-11ea-8d4b-dc71967741ec/LiDARTag-lidar_tag-3.log].

log file: /home/bran/.ros/log/cfd224c6-7980-11ea-8d4b-dc71967741ec/LiDARTag-lidar_tag-3*.log

first:  1  second:  1  Third: 18

[ INFO] [1586340484.094978105]: Apriltag got wrong tags

^C[apriltag3ROS-4] killing on exit
[sync_cam_lidar-2] killing on exit
The apriltag3_ros is over!
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete`

Should I ignore something?
Can you help me?Thanks a lot.

**Comment by brucejk** [comment]
Sure, I am glad to help! 

It looks like you are running a wrong launch file. If you would like to test the LiDARTag package, you should run the provided [launch file](https://github.com/UMich-BipedLab/LiDARTag/blob/06ef534454e5d077bf093dc7bb07ceebd1c6d7d9/launch/LiDARTag.launch#L32) from this package. It got killed by the AprilTag package. 

Please run again and let me know if you have other issues.

**Comment by plumewind** [comment]
OK, I will have a try

**Comment by brucejk** [comment]
I will close it after a few days if you don't encounter any other related issues!

**Comment by plumewind** [comment]
hello,

About the tag, does the calibration tag have requirements for the reflection intensity of the laser? ?
Need specific materials? What material?

Thanks.

**Comment by plumewind** [comment]
hello,

Is intensity information used to extract tag information? ?

Thanks.

**Comment by brucejk** [comment]
Hi, 

You only need to [download](https://drive.google.com/open?id=1Twx7y6yxr-s2qAoCa4XliCxNuINAlXNn) the target images and print them out from a normal printer. 

Currently, intensity information is slightly used in the package but normal inks would work just fine!

**Comment by plumewind** [comment]
Thanks,


I have another question, open in another issue.
