### ISSUE TITLE
error: ‘all’ is not a member of ‘Eigen’

### ISSUE THREAD

**Issue by zzhh00** [UMich-BipedLab/LiDARTag#10]
Hi,
Thanks for your package. I download the `eigen3` from gitlab and checkout the SHA1 you use, but the error always exists when compiling. I am sure the version being used is the right one because I assign the eigen 3.3.9 in `find_package` and it indeed find the right version as below:
`Found TBB: /usr/local/include (found version "2020.2") ` 
`-- =============================================TBB FOUND`
`-- ===============================TBB include_dirs: /usr/local/include`
`-- ===============================TBB includes: `
`-- ===============================TBB libs: `
`-- ===============================TBB libraries: /usr/local/lib/libtbb.so`
`-- ===============================TBB libraries: /usr/local/lib/libtbb.so`
`-- ===============================TBB libs: `
`-- ===============================TBB defs: `
`-- =============================================Eigen final path: /usr/local/include/eigen3`
<br>
Besides, the compile of my small demo which also uses the `Eigen::all` is successful. The small demo has almost the same `CMakeLists.txt` as your package. It means that the version of the found eigen3 is right but  can not work in your package. Below is the CMakeLists.txt of the small demo:
<br>
`cmake_minimum_required(VERSION 2.8 FATAL_ERROR)`

`project(Eigen_test)`

`find_package(Eigen3 3.3.90 REQUIRED)`

`include_directories(${EIGEN3_INCLUDE_DIRS})`
`message(STATUS "=============================================Eigen Path : ${EIGEN3_INCLUDE_DIRS}")`

`add_executable(Eigen_test Eigen_test.cpp)`
<br>
and this is my small demo:
<br>
`#include "Eigen/Core"`
` #include <vector>`
` #include <iostream>`

` int main(void)`
` {`
    ` std::vector<int> ind{4,2,5,5,3};`
     `Eigen::MatrixXi A = Eigen::MatrixXi::Random(4,6);`
    ` std::cout << "Initial matrix A:\n" << A << "\n\n";`
    ` std::cout << "A(all,ind):\n" << A(Eigen::all,ind) << "\n\n";`
    ` return 0;`
` }`
<br>
and this is the compile result:
<br>
`-- =============================================Eigen Path : /usr/local/include/eigen3`
`-- Configuring done`
`-- Generating done`
`-- Build files have been written to: /home/zhehe/test/Eigen_test/build`

`[ 50%] Building CXX object CMakeFiles/Eigen_test.dir/Eigen_test.cpp.o`
`[100%] Linking CXX executable Eigen_test`
`[100%] Built target Eigen_test`
<br>
Can you please help me sovle this issue? Thank you very much.

**Comment by brucejk** [comment]
Hi, 

Thank you for using this package!

I am sorry that you have this issue. Even though I am not an expert in CMake, I will try my best to help! 

The MWV you provided is helpful. Could you please paste your CMakeList.txt of this package?

**Comment by brucejk** [comment]
Hi, 

Thank you for using this package!

I am sorry that you have this issue. Even though I am not an expert in CMake, I will try my best to help! 

It is weird that if this package is using the correct Eigen version, the Eigen should have the API that I use. 
I have several things that I'd like to know:
1. Could you paste the error messages? I'd like to know what is the error from this package. 
2. In addition, the MWV you provided is helpful. Could you please paste your CMakeList.txt of this package? 
3. According to the discussion here #5, there are two versions with the same tag. How many Eigen versions do you have on your computer?

**Comment by brucejk** [comment]
I am going to close this issue. Please feel free to open it again!

**Comment by AmaldevHari** [comment]
I am having similar issue. 
`In file included from /home/sdcnlab/install/workspace/src/LiDARTag/include/lidartag.h:53,
                 from /home/sdcnlab/install/workspace/src/LiDARTag/src/lidartag_decode.cc:37:
/usr/local/include/tbb/tbb.h:21:154: note: ‘#pragma message: TBB Warning: tbb.h contains deprecated functionality. For details, please see Deprecated Features appendix in the TBB reference manual.’
   21 |  please see Deprecated Features appendix in the TBB reference manual.")
      |                                                                       ^

/home/sdcnlab/install/workspace/src/LiDARTag/src/lidartag_decode.cc: In member function ‘void BipedLab::LiDARTag::computeFunctionVectorInnerProductThreading(const MatrixXf&, const int&, const MatrixXf&, const int&, const float&, const float&, const float&, float&)’:
/home/sdcnlab/install/workspace/src/LiDARTag/src/lidartag_decode.cc:843:47: error: ‘all’ is not a member of ‘Eigen’
  843 |         Eigen::MatrixXf test_mat = pc1(Eigen::all, indices);
      |                                               ^~~
/home/sdcnlab/install/workspace/src/LiDARTag/src/lidartag_decode.cc:843:47: note: suggested alternatives:
In file included from /usr/include/boost/algorithm/string.hpp:21,
                 from /usr/include/pcl-1.8/pcl/io/boost.h:66,
                 from /usr/include/pcl-1.8/pcl/io/file_io.h:43,
                 from /usr/include/pcl-1.8/pcl/io/pcd_io.h:44,
                 from /home/sdcnlab/install/workspace/src/LiDARTag/include/lidartag.h:56,
                 from /home/sdcnlab/install/workspace/src/LiDARTag/src/lidartag_decode.cc:37:
/usr/include/boost/algorithm/string/predicate.hpp:438:21: note:   ‘boost::algorithm::all’
  438 |         inline bool all(
      |                     ^~~
/usr/include/boost/algorithm/string/predicate.hpp:438:21: note:   ‘boost::algorithm::all’
/home/sdcnlab/install/workspace/src/LiDARTag/src/lidartag_decode.cc: In lambda function:
/home/sdcnlab/install/workspace/src/LiDARTag/src/lidartag_decode.cc:1032:47: error: ‘all’ is not a member of ‘Eigen’
 1032 |         Eigen::MatrixXf test_mat = pc1(Eigen::all, indices);
      |                                               ^~~
/home/sdcnlab/install/workspace/src/LiDARTag/src/lidartag_decode.cc:1032:47: note: suggested alternatives:
In file included from /usr/include/boost/algorithm/string.hpp:21,
                 from /usr/include/pcl-1.8/pcl/io/boost.h:66,
                 from /usr/include/pcl-1.8/pcl/io/file_io.h:43,
                 from /usr/include/pcl-1.8/pcl/io/pcd_io.h:44,
                 from /home/sdcnlab/install/workspace/src/LiDARTag/include/lidartag.h:56,
                 from /home/sdcnlab/install/workspace/src/LiDARTag/src/lidartag_decode.cc:37:
/usr/include/boost/algorithm/string/predicate.hpp:438:21: note:   ‘boost::algorithm::all’
  438 |         inline bool all(
      |                     ^~~
/usr/include/boost/algorithm/string/predicate.hpp:438:21: note:   ‘boost::algorithm::all’
LiDARTag/CMakeFiles/lidartag_main.dir/build.make:134: recipe for target 'LiDARTag/CMakeFiles/lidartag_main.dir/src/lidartag_decode.cc.o' failed
make[2]: *** [LiDARTag/CMakeFiles/lidartag_main.dir/src/lidartag_decode.cc.o] Error 1
CMakeFiles/Makefile2:2124: recipe for target 'LiDARTag/CMakeFiles/lidartag_main.dir/all' failed
make[1]: *** [LiDARTag/CMakeFiles/lidartag_main.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j20 -l20" failed
`

1. I only have one version of Eigen installed (latest release), I did try with several other version up to 2019 releases
2. I tried going over all the other related issues but couldn't find a solution

**Comment by simonmb** [comment]
I also had this problem. In recent versions `Eigen::all` was first moved to `Eigen::placeholders::all` and then to `Eigen::indexing::all`
c.f. https://eigen.tuxfamily.org/index.php?title=3.4
