### ISSUE TITLE
The link to the motion capture data is invalid

### ISSUE THREAD

**Issue by yorklyb** [UMich-BipedLab/LiDARTag#13]
Hi Jiunn-Kai, I'm trying to get to the motion capture data, however, I found that the link is not valid anymore. It shows me a 404 error. Could you please fix it when you see this? Thanks!

**Comment by brucejk** [comment]
Hi, 

Sorry about the inconvenience! I moved them to another folder and should be under quantitative_results/gt_lidar. 

Or you can find them [here](https://drive.google.com/drive/folders/1_4_JP1s0gbhxyl_V_c4CKJWcwOyUiV5i?usp=sharing)

Please let me know if you have other questions!

**Comment by yorklyb** [comment]
Thanks for your quick reply！ I sent you two emails asking a question regarding the pose estimation. Hope that you could answer my question when you have time. I will close this issue now.
