### ISSUE TITLE
Inquiry into vertices definition

### ISSUE THREAD

**Issue by yorklyb** [UMich-BipedLab/LiDARTag#14]
Sorry to bother you again. But I just compared the vertices estimated by my method and the results in your paper data. I found the x coordinates are quite close and the error is within millimeters. But the dimension of the marker given by my system is smaller than yours. So I'm wondering if we are using the same definition of vertices.  According to your paper, it seems the vertices are the ones of the object.
![image](https://user-images.githubusercontent.com/58899542/148694648-965c82d4-c1e9-4942-96aa-9e8e040bd860.png)
Hence, I feel like the vertices you are using refer to the red points instead of the blue points. I'm wondering if it is correct?
![image](https://user-images.githubusercontent.com/58899542/148694940-79d42ddb-a00e-4998-beb1-e308db8f1608.png)

**Comment by brucejk** [comment]
Yes, the vertex definition is the outer corner (red).

**Comment by yorklyb** [comment]
Hi. In this case, I'm wondering if it is possible to get the ground truth of the blue points. The method I'm using only gives me the positions of the blue points w.r.t the LiDAR frame. So it seems I cannot compare the results with yours directly. Could let me know the ratio and width of the white frame? So maybe I can use some geometric method to process the data in gt_lidar to obtain the ground truth of the blue points. 
![image](https://user-images.githubusercontent.com/58899542/148715275-0d715673-d7c0-4bbe-a80a-93caaac0cda2.png)
By the white frame, I mean the area between the yellow lines. Maybe I also need the size of the marker (the one inside the inner yellow frame)

**Comment by brucejk** [comment]
Hi,  

The target is 8-bit. What you want is the size of 6-bit. You can use a simple geometric interpolation to compute the inner vertices.

**Comment by yorklyb** [comment]
Ok, great. Thanks again!
