### ISSUE TITLE
how to test tag decoding ?

### ISSUE THREAD

**Issue by plumewind** [UMich-BipedLab/LiDARTag#2]
hello,

This is a great idea, I am very interesting in it.

I have read the paper, it can like camera to identify this tag( like apriltag), finally get the full pose of the tag.

The intensity information is  used to get  the unique id code of the tag, used to associate with the april tag from camera?

But, in the code, there is no code to identify this tag, is there no open source?

Thanks a lot.

**Comment by brucejk** [comment]
Hi, 

Intensity information is not currently used to decode an ID in this package. This package is preliminary, only for extracting target points. It is released only for the [automatic calibration pipeline](https://github.com/UMich-BipedLab/automatic_lidar_camera_calibration). Currently, we have a user-define parameter in the launch file, called [distance_threshold](https://github.com/UMich-BipedLab/LiDARTag/blob/a20af5b671981ba53f75c78a27ff71e06e9111cc/launch/LiDARTag.launch#L97) to assign an ID to the clustered blob. This package is an ongoing project and will have the ID decoding finished soon. 

The methods in the [paper](https://arxiv.org/abs/1908.10349) including detection, clustering, decoding,  assume a LiDARTag has to be within the dense area of the LiDAR rings. However, in the [automatic calibration pipeline](https://github.com/UMich-BipedLab/automatic_lidar_camera_calibration), targets are not always in the dense area. Thus, we are currently revising the paper. We would like to relax some constraints and limitations in the paper.

**Comment by plumewind** [comment]
Great！It is cool!
 I am also doing this part of the work, I will continue to pay attention to this package.
