### ISSUE TITLE
Are other tags  useful? 

### ISSUE THREAD

**Issue by plumewind** [UMich-BipedLab/LiDARTag#3]
hello,

I saw the newer pkg, only for tag49h14 and tag16h5, can other tags ?

I read the tag16h5_create(), find it is not look like apriltag decoding, because their  tag16h5.cc are different. Can I add for myself ? How to add?

Can you help me? Thanks a lot.

**Comment by brucejk** [comment]
Sure if you'd like to use other tag families!

We added more constrains when generating tag families. That's why they do not look like the same. 

Could you tell me which ones you want to use? I could possibly generate them for you.

**Comment by plumewind** [comment]
cool，
36h10 and 36h11，thanks !

**Comment by brucejk** [comment]
Hi, 

The tag families *.cc and *.h files are [here](https://drive.google.com/drive/folders/1yykYvQLCmcQBfHMt0cijDTqfrwgZhNJo?usp=sharing). The images of each tag families are [here](https://drive.google.com/drive/folders/1ME21kUxBrsTP2mp6VlnyQIsAk6GD1orz?usp=sharing) and [here](https://drive.google.com/drive/folders/1cBoeeqLjuZBqdfZYWP44Dzzu7k4uL0h3?usp=sharing).

Please let me know if you need anything else! Also, we are still working on the bagfile; will get back to you once we have the results.
