### ISSUE TITLE
unrecognized function 'createDynamicScene' in 'build_LiDARTag_library.m'

### ISSUE THREAD

**Issue by jeongyun0609** [UMich-BipedLab/LiDARTag#7]
Dear Authors,

I want to build my LiDARTag using matlab, but I think createDynamicScene is not define.

If you have this function files, please send me.

Thank you,

**Comment by brucejk** [comment]
Hi,

Please checkout to the `release` branch for the `matlab_utils`. 

Please let me know if the problem still persists or is there anything I could be helpful!

**Comment by brucejk** [comment]
Hi,


Thanks for using this package and open a new issue. I will try my best to help you.

Please pull and checkout to the `release` branch for the [matlab_utils](https://github.com/UMich-BipedLab/matlab_utils).

Please let me know if the problem still persists or is there anything I could be helpful!
